//! Bytes a correct encoder would never produce.
//!
//! Written by hand, because that is the only honest way to prove a decoder
//! refuses what an encoder cannot make. A corpus generated by the encoder under
//! test can only ever demonstrate that it agrees with itself.
//!
//! Every refusal the payload format can produce has at least one vector here,
//! and a test at the end asserts that stays true.

#![allow(clippy::panic, clippy::unwrap_used, reason = "a test reports failure by panicking")]

use enrollment::error::Error;
use enrollment::payload::Joining;

/// A CBOR header for a string of `len` bytes under `major`.
///
/// Minimal width, as the canonical rules require: lengths under 24 live in the
/// initial byte, and anything longer takes the one-byte form.
fn header(major: u8, len: usize) -> Vec<u8> {
    let len = u8::try_from(len).expect("nothing here is that long");
    if len < 24 { vec![major | len] } else { vec![major | 24, len] }
}

/// A CBOR text string.
fn text(value: &str) -> Vec<u8> {
    let mut out = header(0x60, value.len());
    out.extend_from_slice(value.as_bytes());
    out
}

/// A CBOR byte string.
fn bytes(value: &[u8]) -> Vec<u8> {
    let mut out = header(0x40, value.len());
    out.extend_from_slice(value);
    out
}

/// A plausible ed25519 key: the right length, and never mistaken for structure.
fn key(fill: u8) -> Vec<u8> {
    vec![fill; 32]
}

/// The fields of a well-formed payload, in canonical order, as raw pieces.
fn pieces() -> Vec<(Vec<u8>, Vec<u8>)> {
    vec![
        (text("alg"), text("ed25519")),
        (text("name"), text("laptop")),
        (text("sign"), bytes(&key(0x11))),
        (text("relay"), text("https://relay.example")),
        (text("trans"), bytes(&key(0x22))),
        (text("attest"), bytes(&key(0x33))),
    ]
}

/// Assembles a map from pieces, with a stated entry count.
fn map(count: u8, pieces: &[(Vec<u8>, Vec<u8>)]) -> Vec<u8> {
    let mut out = vec![0xa0 | count];
    for (name, value) in pieces {
        out.extend_from_slice(name);
        out.extend_from_slice(value);
    }
    out
}

/// The vectors, each with what it is and why it must be refused.
fn corpus() -> Vec<(&'static str, Vec<u8>)> {
    let mut out = Vec::new();

    out.push(("nothing at all", Vec::new()));

    out.push(("an array where a map belongs", {
        let mut bytes = vec![0x85];
        for (name, value) in pieces() {
            bytes.extend_from_slice(&name);
            bytes.extend_from_slice(&value);
        }
        bytes
    }));

    out.push(("a map claiming more entries than it carries", map(7, &pieces())));
    out.push(("a map claiming fewer entries than it carries", map(5, &pieces())));

    out.push(("a field missing", {
        let mut kept = pieces();
        kept.remove(1);
        map(4, &kept)
    }));

    out.push(("a field repeated", {
        let mut repeated = pieces();
        let duplicate = repeated.first().cloned().expect("a first field");
        repeated.insert(1, duplicate);
        map(6, &repeated)
    }));

    out.push(("fields in the wrong order", {
        let mut swapped = pieces();
        swapped.swap(0, 1);
        map(6, &swapped)
    }));

    out.push(("an unknown field name", {
        let mut renamed = pieces();
        if let Some(entry) = renamed.get_mut(1) {
            entry.0 = text("nome");
        }
        map(6, &renamed)
    }));

    out.push(("an algorithm nobody implements", {
        let mut odd = pieces();
        if let Some(entry) = odd.get_mut(0) {
            entry.1 = text("rsa4096");
        }
        map(6, &odd)
    }));

    out.push(("a signing key of the wrong length", {
        let mut short = pieces();
        if let Some(entry) = short.get_mut(2) {
            entry.1 = bytes(&[0x11; 16]);
        }
        map(6, &short)
    }));

    out.push(("an empty proposed name", {
        let mut empty = pieces();
        if let Some(entry) = empty.get_mut(1) {
            entry.1 = text("");
        }
        map(6, &empty)
    }));

    out.push(("an empty relay address", {
        let mut empty = pieces();
        if let Some(entry) = empty.get_mut(3) {
            entry.1 = text("");
        }
        map(6, &empty)
    }));

    out.push(("a number where a text string belongs", {
        let mut wrong = pieces();
        if let Some(entry) = wrong.get_mut(1) {
            entry.1 = vec![0x01];
        }
        map(6, &wrong)
    }));

    out.push(("trailing bytes after a whole payload", {
        let mut extra = map(6, &pieces());
        extra.push(0x00);
        extra
    }));

    out.push(("a payload larger than the bound", vec![0xa5; 4096]));

    out
}

/// Every vector is refused, and none of them panics or half-decodes.
#[test]
fn every_vector_is_refused() {
    for (what, bytes) in corpus() {
        assert!(
            Joining::decode(&bytes).is_err(),
            "`{what}` was accepted, and a correct encoder cannot produce it"
        );
    }
}

/// The corpus covers the refusals that exist, so a new refusal added without a
/// vector is caught here rather than shipping untested.
#[test]
fn the_corpus_covers_every_refusal_the_format_can_produce() {
    let mut seen_malformed = false;
    let mut seen_too_long = false;
    let mut seen_empty = false;

    for (_, bytes) in corpus() {
        match Joining::decode(&bytes) {
            Err(Error::Malformed(_) | Error::RosterUnusable(_)) => seen_malformed = true,
            Err(Error::TooLong { .. }) => seen_too_long = true,
            Err(Error::Empty(_)) => seen_empty = true,
            Err(_) | Ok(_) => {}
        }
    }

    assert!(seen_malformed, "no vector produces a malformed refusal");
    assert!(seen_too_long, "no vector produces a length refusal");
    assert!(seen_empty, "no vector produces an emptiness refusal");
}

/// The one payload that must be accepted, so the corpus is not passing merely
/// because the decoder refuses everything.
#[test]
fn a_well_formed_payload_is_still_accepted() {
    let decoded = Joining::decode(&map(6, &pieces())).expect("this one is correct");
    assert_eq!(decoded.name, "laptop");
    assert_eq!(decoded.relay, "https://relay.example");
    assert_eq!(decoded.signing.as_bytes(), key(0x11));
    assert_eq!(decoded.transport.as_bytes(), key(0x22));
    assert_eq!(decoded.attestation.as_bytes(), key(0x33));
}
